# Generated by Django 4.2.5 on 2023-09-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_alter_document_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mcqs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
